---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    name: httpbin
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kong/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          # Same as found in Dockerfile's CMD but using an unprivileged port
          command:
          - gunicorn
          - -b
          - 0.0.0.0:8080
          - httpbin:app
          - -k
          - gevent
          env:
          # Tells pipenv to use a writable directory instead of $HOME
          - name: WORKON_HOME
            value: /tmp
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-lb
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin-lb
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 8080
  selector:
    app: httpbin
  type: LoadBalancer
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'httpbin.127-0-0-1.nip.io'
    routes:
    - matchers:
      - exact: /headers
      options:
        ratelimit:
            rateLimits:
              - actions:
                  - genericKey:
                      descriptorValue: "headers-per-minute"      
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system

    - matchers:
      - exact: /get
      options:
        ratelimit:
            rateLimits:
              - actions:
                  - genericKey:
                      descriptorValue: "get-per-minute"      
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system


    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
