---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    name: httpbin
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kong/httpbin
        # - image: quay.io/pflaeging/httpbin:latest-multiarch
          imagePullPolicy: IfNotPresent
          name: httpbin
          # Same as found in Dockerfile's CMD but using an unprivileged port
          command:
          - gunicorn
          - -b
          - 0.0.0.0:8080
          - httpbin:app
          - -k
          - gevent
          env:
          # Tells pipenv to use a writable directory instead of $HOME
          - name: WORKON_HOME
            value: /tmp
          ports:          
          - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: httpbin
    version: v1

#   type: LoadBalancer

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8080
            namespace: gloo-system

# ---
# apiVersion: networking.gloo.solo.io/v1
# kind: Upstream
# metadata:
#   name: httpbin-upstream
#   namespace: gloo-system
# spec:
#   hosts:
#     - addr: httpbin.org # Replace with your actual host if needed
#       port: 80
# ---
# apiVersion: networking.gloo.solo.io/v1
# kind: VirtualService
# metadata:
#   name: httpbin-vs-gw
#   namespace: gloo-system
# spec:
#   virtualHost:
#     domains:
#       - "httpbin.example.com" # Replace with your actual domain or IP address
#     routes:
#       - matchers:
#           - uri:
#               prefix: "/get"
#         routeAction:
#           single:
#             upstream:
#               name: httpbin-upstream
#               namespace: gloo-system