gateway:
  enabled: true
ingress:
  enabled: true
requireIngressClass: true
global:
  istioIntegration:
    disableAutoinjection: true
  istioSDS:
    enabled: true
  glooMtls:
    enabled: true
    istioProxy:
      image:
        registry: docker.io/istio
        repository: proxyv2
        tag: 1.22.0-distroless
    sds:
      image:
        repository: sds
        tag: 1.15.7
gatewayProxies:
  gatewayProxy:
    podTemplate: 
      httpPort: 8080
      httpsPort: 8443

# helm install gloo gloo/gloo -f 99-local-values.yaml --dry-run
# helm install -f myvalues.yaml -f override.yaml  myredis ./redis      