---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gloo
  namespace: kube-system
spec:
  repo: https://storage.googleapis.com/solo-public-helm
  chart: gloo
  version: 1.16.16
  targetNamespace: gloo-system
  createNamespace: true 
  valuesContent: |
    gateway:
      enabled: true
    ingress:
      enabled: false
    settings:
      ratelimitServer:
        rateLimitBeforeAuth: false
        enableXRatelimitHeaders: true
        ratelimitServerRef: # note: the gloo upstream!
          name: gloo-system-rate-limit-8081
          namespace: gloo-system
