---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netshoot
  name: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - image: nicolaka/netshoot
        name: netshoot
        command: ["/bin/bash"]
        args: ["-c", "while true; do ping localhost; sleep 60;done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netshoot-2
  name: netshoot-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot-2
  template:
    metadata:
      labels:
        app: netshoot-2
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: label/nodegroup
                  operator: In
                  values:
                  - infra
      containers:
      - image: nicolaka/netshoot
        name: netshoot
        command: ["/bin/bash"]
        args: ["-c", "while true; do ping localhost; sleep 60;done"]        