---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: calico
  namespace: kube-system
spec:
  repo: https://docs.tigera.io/calico/charts
  chart: tigera-operator
  version: v3.29.1
  targetNamespace: tigera-operator 
  createNamespace: true 
  valuesContent: |
    installation:
      enabled: true
      kubernetesProvider: ""
      cni:
        type: Calico
        ipam:
          type: Calico
      calicoNetwork:
        bgp: Enabled
        containerIPForwarding: Enabled
        nodeAddressAutodetectionV4: 
          interface: eth.*  
        nodeAddressAutodetectionV6: {}
        ipPools:
        - cidr: 172.28.0.0/16
          encapsulation: IPIP
          natOutgoing: Enabled
          nodeSelector: all()