apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        port: 8000
        exposedPort: 8000
            
      websecure:
        port: 8443
        exposedPort: 8443    
                
    ingressClass:  # @schema additionalProperties: false
      enabled: true
      isDefaultClass: false      